name: Bonjour

on: [push]

jobs:
  Salutations:
    name: Salutations
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        env:
          personneASaluer: 'mon voisin Toroto'
        run: echo "Bonjour $(personneASaluer)"
      - name: L'heure de salutation
        run: echo "L'heure était $(date)."
